---
title: "CU Text-as-Data Workshop 2018"
author: "Jeff Jacobs"
date: "November 8, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Columbia University Text-As-Data Workshop 2018

**Thursdays November 8th to December 6th (excluding Thanksgiving week)**

**2:30-4pm in IAB (International Affairs Building) room 707**

Specifically, info for the four sessions is as follows:

1. Thursday November 8, 2:30-4pm, IAB 707
2. Thursday November 15, 2:30-4pm, IAB 707
3. Thursday November 29, 2:30-4pm, IAB 707
4. Thursday December 6, 2:30-4pm, IAB 707

I emailed [this survey](https://goo.gl/forms/N9ES0LlcANSQQaP43) out to get a peek into the minds of people who want to attend the workshop, so that I know things like where to start, what knowledge to assume, and what types of examples or text collections yall would find interesting.

Last but definitely not least, you'll be in a really good spot if you complete this [Interactive R Tutorial](https://www.datacamp.com/courses/free-introduction-to-r) before the first workshop. But I'll still go over the topics briefly just in case.

## Workshop Sessions

1. First Workshop: [A Gentle But SPEEDY Introduction to R](01_Introduction_to_R.html)

2. Second Workshop: [Web Scraping](02_Web_Scraping.html).

3. Third Workshop Part I: [TF-IDF](03_Frequency_Analysis.html)

4. Third Workshop Part II: [Topic Modeling with `ggplot2`](04_Topic_Modeling_ggplot2.html)

5. Fourth Workshop: [Named Entity Recognition](05_Named_Entity_Recognition.html)

* UPDATE: Unfortunately there won't be a Dynamic Topic Modeling tutorial since R doesn't seem to have any library for estimating a DTM. ([Python, on the other hand...](https://radimrehurek.com/gensim/models/ldaseqmodel.html)) So I've replaced it with the [Machine Learning with Text tutorial](06_Machine_Learning.Rmd) below.

## Bonus Material

Stuff I wasn't able to get to during the workshop, plus a few tutorials I've led more recently:

6. [Machine Learning with Text](06_Machine_Learning.html)

7. [Sentiment Analysis](07_Sentiment_Analysis.html)

8. [Stylometry](08_Stylometry.html)

<!--
#### Data analysis redux: *Non*-linear models

glm() and the new (basically) required argument

Refresher on logit, probit, tobit

Simplest logit example
* How to get coeffs as *probabilities* instead of log-odds ratios: use `plogis(model$coefficients))`

#### Text Analysis 2: Sentiment Analysis Boogaloo

## Third Workshop (Now it's all text analysis all the time)

#### Text Analysis 3: topic modeling

Now intro to topic modeling. (Blei figure of NYTimes figures, then Blei figure with colored disks and science article)

Simplest possible topic model project

Simplest possible *dynamic* topic model (if I have time, otherwise next week)

Methods for measuring "Innovation" and "Influence" over time (if I have time)-->

<!--
Finish dynamic topic modeling (if necessary)

WEB SCRAPING. SOCIAL MEDIA DATA. LOUD NOISES.

word2vec social science example

Text analysis *combined* with network analysis

Fun datasets! Do things with them. Go. Now.
-->
